import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@pump.local');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Admin@123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('link', { name: 'Analytics' }).click();
  await page.getByRole('link', { name: 'Setup' }).click();
  await page.getByRole('cell', { name: '5000' }).first().click();
  await page.getByRole('cell', { name: '5000' }).nth(1).click();
  await page.getByRole('cell', { name: '7000' }).click();
  await page.getByRole('cell', { name: '4765' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).fill('pumpoperator@pump.local');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('PumpOperator@123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Session' }).click();
  await page.getByRole('row', { name: 'Unit 1 available M-1, M-2, M-' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Unit 3 available GD-1, GD-2,' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Unit 1 available M-1, M-2, M-' }).getByRole('button').click();
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).first().click();
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).first().fill('1');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).first().press('Tab');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(1).fill('1');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(1).press('Tab');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(2).fill('1');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(2).press('Tab');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(3).fill('1');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(3).press('Tab');
  await page.getByRole('button', { name: 'Start Unit Session' }).click();
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).first().click();
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).first().fill('123456');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).first().press('Tab');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(1).fill('123456');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(1).press('Tab');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(2).fill('123456');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(2).press('Tab');
  await page.getByRole('spinbutton', { name: 'Opening Reading' }).nth(3).fill('123456');
  await page.getByRole('button', { name: 'Start Unit Session' }).click();
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().click();
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().fill('123466');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().press('ControlOrMeta+z');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().fill('123466');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().press('ControlOrMeta+a');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().press('ControlOrMeta+c');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).first().press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().press('Tab');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(1).fill('123466');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(1).press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).press('Tab');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(2).fill('123466');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(2).press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(2).press('Tab');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(3).fill('123466');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(3).press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(3).press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().click();
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().fill('102');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().press('Tab');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(1).fill('1');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(1).press('ControlOrMeta+z');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(1).fill('123466');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(1).press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).fill('102');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).press('Tab');
  await page.getByRole('spinbutton', { name: 'Closing Reading' }).nth(2).press('Tab');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(2).fill('111');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().click();
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().fill('1021');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().press('ControlOrMeta+a');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).first().fill('111');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).dblclick();
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).fill('1021');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).dblclick();
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).click();
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).press('ControlOrMeta+a');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(1).fill('111');
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(3).click();
  await page.getByRole('spinbutton', { name: 'Price Per Litre' }).nth(3).fill('111');
  await page.getByRole('button', { name: 'End Unit Session' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Setup' }).click();
  await page.getByRole('cell', { name: '5000' }).first().click();
  await page.getByRole('cell', { name: '5000' }).nth(1).click();
  await page.getByRole('cell', { name: '7000' }).click();
  await page.getByRole('cell', { name: '4725' }).click();
  await page.getByRole('cell', { name: '7000' }).click();
  await page.getByRole('cell', { name: '5000' }).nth(1).click();
  await page.getByRole('cell', { name: '5000' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('pumpoperator');
  await page.getByRole('button', { name: 'Login' }).click();
});